import Head from 'next/head'
import Feed from '../Components/Feed'
import Sidebar from '../Components/Sidebar'
import Modal from '../Components/Modal'
import { getProviders, getSession, useSession } from "next-auth/react";
import Login from '../Components/Login'
import { modalState } from "../atoms/modalAtom";
import { useRecoilState } from "recoil";
import Widgets from '../Components/Widgets';

export default function Home({trendingResults, followResults, providers}) {
  const { data: session } = useSession();
  const [isOpen, setIsOpen] = useRecoilState(modalState);

  
  if (!session) return <Login providers={providers} />;

  return (
    <div className="">
      <Head>
        <title>twitterproj</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon -.ico" />
      </Head>



    <main  className="bg-black min-h-screen flex m-w-[1500px] mx-auto">
        {/* Sidebar */}
        <Sidebar />

          {/* Feed  */}
            <Feed />

            {/* Widgets */}
              <Widgets 
               trendingResults={trendingResults}
               followResults={followResults} /> 
              
              {/*Modal */}
             {isOpen && <Modal />} 
    </main>
      
    </div>
  )
}


export async function getServerSideProps(context) {
  const trendingResults = await fetch( "https://api.twitter.com/1.1/trends/available.json").then(
    (res) => res.json()
  );
  const followResults = await fetch( "https://api.twitter.com/2/users/:id/following").then(
    (res) => res.json()
  );
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      trendingResults,
      followResults,
      providers,
      session,
    },
  };
}